---

- name:  Install Docker dependencies
  apt:
    update_cache: yes
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - software-properties-common
    - apt-transport-https

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
      
- name: Add Docker APT repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"

- name: Install Docker
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Ensure docker group exists
  group:
    name: docker

- name: Ensure {{ owner }} belongs to docker group
  user:
    name: "{{ owner }}"
    groups: docker
    append: yes

